In [21]:
import pandas as pd
import requests
import json

In [8]:
test = pd.read_csv("data/test.csv")

test.drop(columns=['CustomerID'], inplace=True)
test.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled
0,38,17.869374,679.036195,Premium,Mailed check,No,TV Shows,No,TV,29.126308,122.274031,42,Comedy,3.522724,2,Male,23,No,No
1,77,9.912854,763.289768,Basic,Electronic check,Yes,TV Shows,No,TV,36.873729,57.093319,43,Action,2.021545,2,Female,22,Yes,No
2,5,15.019011,75.095057,Standard,Bank transfer,No,TV Shows,Yes,Computer,7.601729,140.414001,14,Sci-Fi,4.806126,2,Female,22,No,Yes
3,88,15.357406,1351.451692,Standard,Electronic check,No,Both,Yes,Tablet,35.586430,177.002419,14,Comedy,4.943900,0,Female,23,Yes,Yes
4,91,12.406033,1128.949004,Standard,Credit card,Yes,TV Shows,Yes,Tablet,23.503651,70.308376,6,Drama,2.846880,6,Female,0,No,No

In [28]:
test['json'] = test.to_json(orient='records', lines=True).splitlines()
test['json']

0         {"AccountAge":38,"MonthlyCharges":17.869373540...
1         {"AccountAge":77,"MonthlyCharges":9.9128541321...
2         {"AccountAge":5,"MonthlyCharges":15.0190113186...
3         {"AccountAge":88,"MonthlyCharges":15.357405588...
4         {"AccountAge":91,"MonthlyCharges":12.40603301,...
                                ...
104475    {"AccountAge":80,"MonthlyCharges":17.348235910...
104476    {"AccountAge":20,"MonthlyCharges":8.2754590067...
104477    {"AccountAge":106,"MonthlyCharges":18.13434306...
104478    {"AccountAge":46,"MonthlyCharges":19.774009872...
104479    {"AccountAge":110,"MonthlyCharges":7.438385445...
Name: json, Length: 104480, dtype: object

In [29]:
customer = json.loads(test['json'][0])

In [31]:
url = "http://127.0.0.1:9696/predict"
requests.post(url, json=customer).json()

{'Churn probability': 0.4566885232925415}